### ISSUE TITLE
bug: Caffeine not able to connect to screen

### ISSUE THREAD

**Issue by Tchekda** [nix-community/home-manager#3038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

When starting via the service or manually in the cmd, here is the error : 
```
Traceback (most recent call last):
  File "/nix/store/1rbzj4r73izd3zi2vkwd8f2b8ab3qblw-caffeine-ng-3.5.1/bin/..caffeine-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/1rbzj4r73izd3zi2vkwd8f2b8ab3qblw-caffeine-ng-3.5.1/lib/python3.9/site-packages/caffeine/main.py", line 454, in main
    main = GUI(arguments["--preferences"])
  File "/nix/store/1rbzj4r73izd3zi2vkwd8f2b8ab3qblw-caffeine-ng-3.5.1/lib/python3.9/site-packages/caffeine/main.py", line 155, in __init__
    self.__core = Caffeine(self.__process_manager)
  File "/nix/store/1rbzj4r73izd3zi2vkwd8f2b8ab3qblw-caffeine-ng-3.5.1/lib/python3.9/site-packages/caffeine/core.py", line 82, in __init__
    self._ewmh = EWMH()
  File "/nix/store/sm0s5mcfb86mz3jjjabqj5wds5nc39df-python3.9-ewmh-0.1.6/lib/python3.9/site-packages/ewmh/ewmh.py", line 70, in __init__
    self.display = _display or display.Display()
  File "/nix/store/j1w041npm5paz1rsk92bqz33c3b65hkm-python3.9-xlib-0.31/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/nix/store/j1w041npm5paz1rsk92bqz33c3b65hkm-python3.9-xlib-0.31/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/nix/store/j1w041npm5paz1rsk92bqz33c3b65hkm-python3.9-xlib-0.31/lib/python3.9/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":1": b'Authorization required, but no authorization protocol specified\n'`
```
I tried with the previous version (2.4.5) but same error.

Bug appeared when I update the laptop to 22.05

### Maintainer CC

@marzipankaiser @uvNikita 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.18.0, NixOS, 22.05 (Quokka), 22.05.538.d9794b04bff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(tchekda): `"home-manager-22.05.tar.gz, home-manager-master, nixos-22.05, nixos-21.11-21.11, nixos-unstable, unstable"`
 - channels(root): `"home-manager-22.05.tar.gz, home-manager-master, nixos-22.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by uvNikita** [comment]
Can you try to remove `~/.xauth*` files from your user's home directory? I vaguely remember that it helped with errors like this.

**Comment by Tchekda** [comment]
> Can you try to remove `~/.xauth*` files from your user's home directory? I vaguely remember that it helped with errors like this.

I removed `~/.Xauthority` but still same error
