### ISSUE TITLE
bug: atuin: bats@1.8.2 results in failing build

### ISSUE THREAD

**Issue by montchr** [nix-community/home-manager#3511]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I've been running into a nearly identical issue as #2437  with `atuin` and `bash-preexec` since updating `nixos-unstable` to a commit made sometime between https://github.com/NixOS/nixpkgs/commit/1710ed1f6f8ceb75cf7d1cf55ee0cc21760e1c7a and https://github.com/NixOS/nixpkgs/commit/04f574a1c0fde90b51bf68198e2297ca4e7cccf4 on `nixos-unstable`.

Minimal reproduction (on `aarch64-darwin` but the flake should work on other systems):

https://git.sr.ht/~montchr/hm-atuin-failure/tree/main/item/flake.nix

### Error

```console
error: builder for '/nix/store/mbhf127fac9789yis4gjf9rdmrg55rqx-setuptools-44.0.0-sdist.tar.gz.drv'failed with exit code 1;
       last 10 log lines:
       > Traceback (most recent call last):
       >   File "bootstrap.py", line 64, in <module>
       >     __name__ == '__main__' and main()
       >   File "bootstrap.py", line 61, in main
       >     run_egg_info()
       >   File "bootstrap.py", line 54, in run_egg_info
       >     subprocess.check_call(cmd)
       >   File "/nix/store/jq89wc0cq3wwj08sfs0m1apfwbk9vvw4-python-2.7.18.5/lib/python2.7/subprocess.py", line 190, in check_call
       >     raise CalledProcessError(retcode, cmd)
       > subprocess.CalledProcessError: Command '['/nix/store/jq89wc0cq3wwj08sfs0m1apfwbk9vvw4-python-2.7.18.5/bin/python2.7', u'setup.py', u'egg_info']' returned non-zero exit status 1
       For full logs, run 'nix log /nix/store/mbhf127fac9789yis4gjf9rdmrg55rqx-setuptools-44.0.0-sdist.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/p6pjqvsh094522gpljl0lgfl3y5zsmq2-python2.7-bootstrapped-pip-20.3.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7kp1g21k2lxnks3y0i0zccxrxghyvcbx-python2.7-setuptools-44.0.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gfvrkw5a0h0f604p7gldnd3knl1h6vgy-python-catch-conflicts-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/a73q3cis3fn6rp4mza9fc29nagjji5lm-python2.7-pip-20.3.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/69gv71a1iai34jdcqhminjnvg2db7v9y-setuptools-setup-hook.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ffcl7ab68djwq0zgyy6n2qw85rdb2vdd-resholve-0.8.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/75wyjwc75xijhs52sbxvx86cisxafm9p-bats-1.8.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/g2rnc55qplscfjja3k3iwilvi14qspc7-bash-preexec-0.5.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hml6nzn9cpvp4d5qzfhlibjqjspryyp3-bashrc.drv' failedto build
error: 1 dependencies of derivation '/nix/store/himv35x5ad4yr6w8wadmz6lw678m76k4-home-manager-files.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dkn5bcfqcivqvghj7phrp8dwwk3dpwps-home-manager-generation.drv' failed to build
```

### Log output for failing `setuptools-44.0.0-sdist` derivation

```console
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/vp039y542nr4qq62lxm7d3sd4piix1fi-setuptools-44.0.0-source
source root is setuptools-44.0.0-source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/0qzs4kq2lvl09k80nf54bl00hd2ylfam-tag-date.patch
patching file setup.cfg
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
adding minimal entry_points
Regenerating egg_info
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import setuptools
  File "/private/tmp/nix-build-setuptools-44.0.0-sdist.tar.gz.drv-0/setuptools-44.0.0-source/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/private/tmp/nix-build-setuptools-44.0.0-sdist.tar.gz.drv-0/setuptools-44.0.0-source/setuptools/dist.py", line 36, in <module>
    from setuptools import windows_support
  File "/private/tmp/nix-build-setuptools-44.0.0-sdist.tar.gz.drv-0/setuptools-44.0.0-source/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/nix/store/jq89wc0cq3wwj08sfs0m1apfwbk9vvw4-python-2.7.18.5/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes
Traceback (most recent call last):
  File "bootstrap.py", line 64, in <module>
    __name__ == '__main__' and main()
  File "bootstrap.py", line 61, in main
    run_egg_info()
  File "bootstrap.py", line 54, in run_egg_info
    subprocess.check_call(cmd)
  File "/nix/store/jq89wc0cq3wwj08sfs0m1apfwbk9vvw4-python-2.7.18.5/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/jq89wc0cq3wwj08sfs0m1apfwbk9vvw4-python-2.7.18.5/bin/python2.7', u'setup.py', u'egg_info']' returned non-zero exit status 1
```

### Maintainer CC

@hawkw
also @rycee since you looked into #2437 and submitted https://github.com/NixOS/nixpkgs/pull/144161 and https://github.com/rcaloras/bash-preexec/issues/121

### System information

```markdown
this path will be fetched (0.01 MiB download, 0.04 MiB unpacked):
  /nix/store/ggx0s7mwf0i8px7c8f4ri3zhi8v8y0aq-stdenv-darwin
copying path '/nix/store/ggx0s7mwf0i8px7c8f4ri3zhi8v8y0aq-stdenv-darwin' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.6.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(cdom): `"home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/xvxl5p5cw7yr3hbc96dld045l6l467hs-dk1bqlz87dzsd8g4fq92pscgd60ji2vr-source`
```

This is coming from a flake whose nixpkgs is tracking `nixos-unstable`.

**Comment by montchr** [comment]
@abathur Yup, works fine now. Thanks.
