### ISSUE TITLE
bug: services.caffeine does not start

### ISSUE THREAD

**Issue by davisrichard437** [nix-community/home-manager#4696]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

(

`services.caffeine` does not start on my NixOS machine (information below) or on my non-NixOS machine running home-manager. I get the following information from `journalctl --user -xeu caffeine.service`:

```
Nov 24 01:23:21 nixos-laptop caffeine[3336]: Authorization required, but no authorization protocol specified
Nov 24 01:23:21 nixos-laptop caffeine[3336]: Authorization required, but no authorization protocol specified
Nov 24 01:23:21 nixos-laptop .caffeine-wrapp[3336]: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Nov 24 01:23:21 nixos-laptop caffeine[3336]: Traceback (most recent call last):
Nov 24 01:23:21 nixos-laptop caffeine[3336]:   File "/nix/store/b51dkmky2ab80zyjprffwlxvnz9f08hf-caffeine-ng-4.2.0/bin/.caffeine-wrapped", line 4, in <module>
Nov 24 01:23:21 nixos-laptop caffeine[3336]:     from caffeine.cli import cli
Nov 24 01:23:21 nixos-laptop caffeine[3336]:   File "/nix/store/b51dkmky2ab80zyjprffwlxvnz9f08hf-caffeine-ng-4.2.0/lib/python3.11/site-packages/caffeine/cli.>
Nov 24 01:23:21 nixos-laptop caffeine[3336]:     from caffeine.main import GUI
Nov 24 01:23:21 nixos-laptop caffeine[3336]:   File "/nix/store/b51dkmky2ab80zyjprffwlxvnz9f08hf-caffeine-ng-4.2.0/lib/python3.11/site-packages/caffeine/main>
Nov 24 01:23:21 nixos-laptop caffeine[3336]:     generic = icon_theme.load_icon(
Nov 24 01:23:21 nixos-laptop caffeine[3336]:               ^^^^^^^^^^^^^^^^^^^^
Nov 24 01:23:21 nixos-laptop caffeine[3336]: AttributeError: 'NoneType' object has no attribute 'load_icon'
Nov 24 01:23:21 nixos-laptop systemd[3072]: caffeine.service: Main process exited, code=exited, status=1/FAILURE
```

However, when running the `caffriene` binary listed in the service file `~/.config/systemd/user/caffeine.service`, the program runs just fine. I can only assume that some aspect of the service configuration renders it unable to start properly, though I do not know enough about systemd services to know for certain which and why.

After a little bit of trial and error I was able to identify that the issue is the `ProtectHome=yes` line. I will subsequently open a pull request with this change, though if there is a better way to do this I defer to those more experienced than I.

### Maintainer CC

@uvNikita (I think)

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 24.05 (Uakari), 24.05.20231122.19cbff5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by davisrichard437** [comment]
An update: it seems to start without issue on Wayland, the issue seems to be X only

**Comment by symphorien** [comment]
I am also affected, on NixOS 23.11 and xfce+i3.

**Comment by rycee** [comment]
@symphorien I've backported the above PR to the release-23.11 branch. Please update and give it a try.

**Comment by symphorien** [comment]
thank you it works!

**Comment by sumnerevans** [comment]
This appears to have been completed by https://github.com/nix-community/home-manager/pull/4698

**Comment by marie-bnl** [comment]
I am having this issue again despite `ProtectHome` having been removed.

**Service status**

```
[marie@Marie-ThinkPad:~]$ systemctl --user status caffeine.service
× caffeine.service - caffeine
     Loaded: loaded (/home/marie/.config/systemd/user/caffeine.service; enabled; preset: ignored)
     Active: failed (Result: exit-code) since Wed 2026-02-11 00:02:11 CET; 4min 5s ago
   Duration: 332ms
 Invocation: ebd5d5b0df474bc09d4e8bd59dac8504
    Process: 430903 ExecStart=/nix/store/bkjv8p302g7hr3xz8rq0v7a0934i6pi8-caffeine-ng-4.2.0/bin/caffeine (code=exited, status=1/FAILURE)
   Main PID: 430903 (code=exited, status=1/FAILURE)
   Mem peak: 22.6M
        CPU: 362ms

Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: caffeine.service: Scheduled restart job, restart counter is at 5.
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: caffeine.service: Start request repeated too quickly.
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: caffeine.service: Failed with result 'exit-code'.
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: Failed to start caffeine.
```

**Journal**

```
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: Starting caffeine...
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: Started caffeine.
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]: Authorization required, but no authorization protocol specified
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]: Authorization required, but no authorization protocol specified
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]: Traceback (most recent call last):
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]:   File "/nix/store/bkjv8p302g7hr3xz8rq0v7a0934i6pi8-caffeine-ng-4.2.0/bin/.caffeine-wrapped", line 4, in <m>
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]:     from caffeine.cli import cli
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]:   File "/nix/store/bkjv8p302g7hr3xz8rq0v7a0934i6pi8-caffeine-ng-4.2.0/lib/python3.13/site-packages/caffeine>
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]:     from caffeine.main import GUI
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]:   File "/nix/store/bkjv8p302g7hr3xz8rq0v7a0934i6pi8-caffeine-ng-4.2.0/lib/python3.13/site-packages/caffeine>
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]:     generic = icon_theme.load_icon(
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]:               ^^^^^^^^^^^^^^^^^^^^
Feb 11 00:02:11 Marie-ThinkPad caffeine[430903]: AttributeError: 'NoneType' object has no attribute 'load_icon'
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: caffeine.service: Main process exited, code=exited, status=1/FAILURE
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: caffeine.service: Failed with result 'exit-code'.
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: caffeine.service: Scheduled restart job, restart counter is at 5.
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: caffeine.service: Start request repeated too quickly.
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: caffeine.service: Failed with result 'exit-code'.
Feb 11 00:02:11 Marie-ThinkPad systemd[2306]: Failed to start caffeine.
```

**Service file**

```
[marie@Marie-ThinkPad:~]$ cat /home/marie/.config/systemd/user/caffeine.service;
[Install]
WantedBy=graphical-session.target

[Service]
ExecStart=/nix/store/bkjv8p302g7hr3xz8rq0v7a0934i6pi8-caffeine-ng-4.2.0/bin/caffeine
PrivateTmp=true
ProtectSystem=full
Restart=on-failure
Slice=session.slice
Type=exec

[Unit]
Description=caffeine
```

I am trying to run it under Xorg. I don't have a tray but I don't think that would be the issue.
